#ifndef _VENDINGMACHINESTATE_H_
#define _VENDINGMACHINESTATE_H_

enum VendingMachineState
{
    VENDINGMACHINESTATE_TURNEDOFF = 0,
    VENDINGMACHINESTATE_WAITING = 1,
    VENDINGMACHINESTATE_ACCEPTINGPAYMENT = 2,
    VENDINGMACHINESTATE_VALIDATINGORDER = 3,
    VENDINGMACHINESTATE_COOKING = 4
};

#endif // _VENDINGMACHINESTATE_H_
